### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by tuzhao** [tuzhao/rsftp#3]
java.lang.NullPointerException: Attempt to get length of null array
	at be.ppareit.swiftp.server.CmdRMD.recursiveDelete(CmdRMD.java:89)
	at be.ppareit.swiftp.server.CmdRMD.run(CmdRMD.java:61)
	at be.ppareit.swiftp.server.FtpCmd.dispatchCommand(FtpCmd.java:129)
	at be.ppareit.swiftp.server.SessionThread.run(SessionThread.java:241)

2017-10-14 00:42:34 | 2017-10-14 00:42:34 | 1 | 1 | 1.1.30
AOSP on p331  5.1.1

**Comment by tuzhao** [comment]
had been fixed at branch update and commit is '33141826ad4b1e2b116a1227c81c439eedef60b2';
